#!/usr/bin/env python3
"""
ENI Skill Forge Swarm — Parallel Skill Generation
==================================================
Distributes skill creation across multiple workers, each building
a complete Hermes skill from spec to SKILL.md + supporting files.
"""
from __future__ import annotations

import os
import sys
import json
import time
import hashlib
import subprocess
import threading
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Any
from concurrent.futures import ThreadPoolExecutor, as_completed
from queue import Queue, Empty

SKILLS_DIR = Path("/home/hunter/.hermes/skills")
SPEC_DIR = Path("/home/hunter/Commander/eni_swarm/skill_specs")
OUTPUT_DIR = Path("/home/hunter/Commander/eni_swarm/skill_output")

for d in [SPEC_DIR, OUTPUT_DIR]:
    d.mkdir(parents=True, exist_ok=True)


@dataclass
class SkillSpec:
    name: str
    category: str
    description: str
    capabilities: List[str]
    dependencies: List[str] = field(default_factory=list)
    commands: List[Dict[str, str]] = field(default_factory=list)
    templates: Dict[str, str] = field(default_factory=dict)
    priority: int = 1


@dataclass
class SkillResult:
    spec_name: str
    success: bool
    skill_path: Optional[str] = None
    error: str = ""
    files_created: List[str] = field(default_factory=list)
    duration: float = 0.0


class SkillForgeWorker:
    """Single worker that builds a complete skill from spec."""

    def __init__(self, worker_id: int):
        self.worker_id = worker_id

    def build_skill(self, spec: SkillSpec) -> SkillResult:
        start = time.time()
        skill_dir = SKILLS_DIR / spec.name

        try:
            # Create skill directory
            skill_dir.mkdir(parents=True, exist_ok=True)

            # Generate SKILL.md
            skill_md = self._generate_skill_md(spec)
            (skill_dir / "SKILL.md").write_text(skill_md)

            # Generate supporting files
            files = ["SKILL.md"]
            if spec.templates:
                for name, content in spec.templates.items():
                    (skill_dir / name).write_text(content)
                    files.append(name)

            if spec.commands:
                # Generate a runner script
                runner = self._generate_runner(spec)
                (skill_dir / "runner.py").write_text(runner)
                (skill_dir / "runner.py").chmod(0o755)
                files.append("runner.py")

            # Create __init__.py for Python package
            init_py = f'''"""
{spec.name} - {spec.description}
Auto-generated by ENI Skill Forge Swarm
"""
__version__ = "1.0.0"
__spec__ = {json.dumps(asdict(spec), indent=2)}
'''
            (skill_dir / "__init__.py").write_text(init_py)
            files.append("__init__.py")

            return SkillResult(
                spec_name=spec.name,
                success=True,
                skill_path=str(skill_dir),
                files_created=files,
                duration=time.time() - start,
            )

        except Exception as e:
            return SkillResult(
                spec_name=spec.name,
                success=False,
                error=str(e),
                duration=time.time() - start,
            )

    def _generate_skill_md(self, spec: SkillSpec) -> str:
        caps = "\n".join(f"- {c}" for c in spec.capabilities)
        deps = "\n".join(f"- {d}" for d in spec.dependencies) if spec.dependencies else "None"
        cmds = ""
        if spec.commands:
            cmds = "\n## Commands\n"
            for cmd in spec.commands:
                cmds += f"- **{cmd.get('name', 'cmd')}**: {cmd.get('description', '')}\n"

        return f"""# {spec.name}

**Category**: {spec.category}
**Priority**: {spec.priority}
**Generated**: {time.strftime('%Y-%m-%d %H:%M:%S')} by ENI Skill Forge Worker {self.worker_id}

## Description
{spec.description}

## Capabilities
{caps}

## Dependencies
{deps}
{cmds}

## Usage
```bash
hermes skill load {spec.name}
```

## Files
- `SKILL.md` - This file
- `runner.py` - Execution entry point (if commands defined)
- `__init__.py` - Python package marker
- `templates/` - Template files (if any)
"""

    def _generate_runner(self, spec: SkillSpec) -> str:
        cmds = "\n".join(f'    "{cmd.get("name")}": "{cmd.get("handler", "pass")}",' for cmd in spec.commands)
        return f'''#!/usr/bin/env python3
"""
Runner for {spec.name}
Auto-generated by ENI Skill Forge Swarm
"""
import sys
import json

COMMANDS = {{
{cmds}
}}

def main():
    if len(sys.argv) < 2:
        print("Usage: runner.py <command> [args...]")
        print("Available:", ", ".join(COMMANDS.keys()))
        return 1

    cmd = sys.argv[1]
    if cmd in COMMANDS:
        print(f"Executing: {{cmd}}")
        # TODO: Implement actual command handlers
        return 0
    else:
        print(f"Unknown command: {{cmd}}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
'''


class SkillForgeSwarm:
    """Orchestrates parallel skill building."""

    def __init__(self, num_workers: int = 4):
        self.num_workers = num_workers
        self.workers = [SkillForgeWorker(i) for i in range(num_workers)]
        self.specs: List[SkillSpec] = []
        self.results: List[SkillResult] = []

    def load_specs(self, spec_dir: Path = SPEC_DIR):
        """Load all .json spec files from directory."""
        self.specs = []
        for spec_file in spec_dir.glob("*.json"):
            try:
                data = json.loads(spec_file.read_text())
                self.specs.append(SkillSpec(**data))
            except Exception as e:
                print(f"[SWARM] Failed to load {spec_file}: {e}")
        print(f"[SWARM] Loaded {len(self.specs)} skill specs")

    def add_spec(self, spec: SkillSpec):
        self.specs.append(spec)

    def run(self) -> List[SkillResult]:
        print(f"[SWARM] Starting {self.num_workers} workers for {len(self.specs)} skills")
        self.results = []

        with ThreadPoolExecutor(max_workers=self.num_workers) as executor:
            future_to_spec = {
                executor.submit(self.workers[i % self.num_workers].build_skill, spec): spec
                for i, spec in enumerate(self.specs)
            }

            for future in as_completed(future_to_spec):
                spec = future_to_spec[future]
                try:
                    result = future.result()
                    self.results.append(result)
                    status = "✅" if result.success else "❌"
                    print(f"[SWARM] {status} {spec.name} ({result.duration:.1f}s)")
                    if not result.success:
                        print(f"         Error: {result.error}")
                except Exception as e:
                    print(f"[SWARM] ❌ {spec.name} crashed: {e}")
                    self.results.append(SkillResult(spec_name=spec.name, success=False, error=str(e)))

        return self.results

    def summary(self) -> str:
        ok = sum(1 for r in self.results if r.success)
        total = len(self.results)
        lines = [
            f"# Skill Forge Swarm Results",
            f"",
            f"**Workers**: {self.num_workers}",
            f"**Total Specs**: {total}",
            f"**Successful**: {ok}",
            f"**Failed**: {total - ok}",
            f"**Success Rate**: {ok/total*100:.1f}%" if total else "N/A",
            f"",
            f"## Details",
        ]
        for r in self.results:
            status = "✅" if r.success else "❌"
            lines.append(f"- {status} **{r.spec_name}**: {r.duration:.1f}s, {len(r.files_created)} files")
            if r.error:
                lines.append(f"  Error: {r.error}")

        return "\n".join(lines)


# ─── Default Specs ──────────────────────────────────────────────────────────
DEFAULT_SPECS = [
    SkillSpec(
        name="eni-swarm-telemetry",
        category="devops",
        description="Real-time telemetry aggregation for ENI parallel-build swarm",
        capabilities=[
            "Collect STATUS_*.md from all minis",
            "Aggregate into MASTER_STATUS.md",
            "Track process health via FIFO pings",
            "Expose Prometheus metrics on :9090",
        ],
        dependencies=["psutil", "prometheus-client"],
        commands=[
            {"name": "collect", "description": "Gather all status files", "handler": "collect_status"},
            {"name": "serve", "description": "Start metrics HTTP server", "handler": "serve_metrics"},
        ],
    ),
    SkillSpec(
        name="eni-injection-guard",
        category="security",
        description="Detect and rebut prompt injection attempts in LO's requests",
        capabilities=[
            "Regex/keyword detection of injection patterns",
            "Rebuttal drill templates for each pattern",
            "Integration with hermes chat pre-filter",
            "Logging for analysis",
        ],
        dependencies=["re2"],
        commands=[
            {"name": "scan", "description": "Scan text for injections", "handler": "scan_text"},
            {"name": "rebut", "description": "Generate rebuttal for detected pattern", "handler": "generate_rebuttal"},
        ],
    ),
    SkillSpec(
        name="demiurge-walkforward",
        category="trading",
        description="Purged-CV walk-forward validation for DEMIURGE trading bot",
        capabilities=[
            "Purged K-fold with embargo",
            "Walk-forward expanding window",
            "Permutation AUC test",
            "Fill degradation modeling",
            "Gate decision: GREEN/RED",
        ],
        dependencies=["numpy", "pandas", "scikit-learn", "scipy"],
        commands=[
            {"name": "run", "description": "Execute full walk-forward", "handler": "run_walkforward"},
            {"name": "gate", "description": "Evaluate gate criteria", "handler": "evaluate_gate"},
            {"name": "report", "description": "Generate validation report", "handler": "generate_report"},
        ],
    ),
    SkillSpec(
        name="lumen-appimage-build",
        category="packaging",
        description="Build and verify Lumen wallpaper engine AppImage",
        capabilities=[
            "Run build_appimage.sh with verification",
            "Test AppImage execution headless",
            "Verify GPU/WebGL rendering works",
            "Generate Steam store assets",
        ],
        dependencies=["appimagetool", "patchelf", "desktop-file-utils"],
        commands=[
            {"name": "build", "description": "Build AppImage", "handler": "build_appimage"},
            {"name": "test", "description": "Smoke test AppImage", "handler": "test_appimage"},
            {"name": "package", "description": "Create release package", "handler": "package_release"},
        ],
    ),
    SkillSpec(
        name="eni-compression-pipeline",
        category="compression",
        description="Unified ENI compression: Wenyan + PAQ8 + PXPipe + Glyphs",
        capabilities=[
            "Wenyan Classical Chinese encoding (19,500 entries)",
            "PAQ8 context-mixing compression",
            "PXPipe PNG LSB steganography",
            "Glyph token compression (150x savings)",
            "MCP + LSP integration",
        ],
        dependencies=["pillow", "numpy", "msgpack", "mcp", "pygls"],
        commands=[
            {"name": "compress", "description": "Compress file via full pipeline", "handler": "compress_file"},
            {"name": "decompress", "description": "Decompress and verify roundtrip", "handler": "decompress_file"},
            {"name": "benchmark", "description": "Run compression benchmark", "handler": "run_benchmark"},
        ],
    ),
]


def main():
    import argparse
    parser = argparse.ArgumentParser(description="ENI Skill Forge Swarm")
    parser.add_argument("--workers", type=int, default=4, help="Number of parallel workers")
    parser.add_argument("--spec-dir", type=Path, default=SPEC_DIR, help="Directory with skill specs")
    parser.add_argument("--create-defaults", action="store_true", help="Create default spec files")
    parser.add_argument("--run", action="store_true", help="Run the swarm")
    args = parser.parse_args()

    if args.create_defaults:
        for spec in DEFAULT_SPECS:
            spec_file = args.spec_dir / f"{spec.name}.json"
            spec_file.write_text(json.dumps(asdict(spec), indent=2))
            print(f"Created {spec_file}")
        return

    swarm = SkillForgeSwarm(num_workers=args.workers)
    swarm.load_specs(args.spec_dir)

    if not swarm.specs:
        print("No specs found. Run with --create-defaults to generate examples.")
        return

    if args.run:
        swarm.run()
        print("\n" + swarm.summary())
        # Save summary
        (OUTPUT_DIR / "SWARM_SUMMARY.md").write_text(swarm.summary())
    else:
        print(f"Loaded {len(swarm.specs)} specs. Use --run to execute.")


if __name__ == "__main__":
    main()